target 'iOS' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'core', :path => '../core'
  pod 'coreSwift', :path => '../core'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'CodeScanner', :git => 'https://github.com/Luteoos/CodeScanner.git', :tag => '2.3.7' # rework resource bundling
  pod 'OneSignal/OneSignal', '>= 5.0.0', '< 6.0'
  pod 'OneSignal/OneSignalInAppMessages', '>= 5.0.0', '< 6.0'
end

target 'macOs' do
  use_frameworks!
#  platform :ios, '14.1'
  platform :macos, '13.3'
  pod 'core', :path => '../core'
  pod 'coreSwift', :path => '../core'
#  pod 'FirebaseAnalytics'
#  pod 'FirebaseCrashlytics'
#  pod 'CodeScanner', :git => 'https://github.com/Luteoos/CodeScanner.git', :tag => '2.3.7' # rework resource bundling
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks! #:linkage => :static
  platform :ios, '14.1'
  pod 'OneSignal/OneSignal', '>= 5.0.0', '< 6.0'
  pod 'OneSignal/OneSignalInAppMessages', '>= 5.0.0', '< 6.0'
end
